# Generated by Django 4.1 on 2022-08-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0003_course_pricing_tiers_pricing_currency_pricing_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="course", name="subtitle", field=models.TextField(),
        ),
    ]
